name: Smoke Tests (Saucelabs)

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Update to v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2 # Update to v2
        with:
          distribution: 'temurin' # 'temurin' distribution provides OpenJ9 builds of the OpenJDK
          java-version: '17'

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install Chrome for Testing and its driver
        run: |
          npm i puppeteer
          npx @puppeteer/browsers install chrome@stable

      - name: Snapshot Build
        run: mvn clean install -T4 -DskipTests

      - name: Smoke Tests
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_WEBSERVICE_URL: ${{ secrets.JIRA_WEBSERVICE_URL }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
        run: cd serenity-smoketests && mvn -B verify -Denvironment=saucelabs -Dsaucelabs.username=${{ secrets.SAUCELABS_USER }} -Dsaucelabs.accessKey=${{ secrets.SAUCELABS_KEY }}
